### ISSUE TITLE
Support other type of TODO-comments

### ISSUE THREAD

**Issue by rollecode** [SolomonRosemite/TypeScript-Todo#10]
Right now this extension supports: `// TODO: Something`. However, it doesn't seem to notice comments like this (php):

```php
/**
 * TODO: Add here the name and meaning of this file, hero.php
 *
 * TODO: Add description here for this file called hero.
 **/
```

Possible to add support for these?

**Comment by rollecode** [comment]
Or then something is broken, because the earlier shown scss comments are not catched also:

```scss
// TODO: To code review session on Friday
del {
  margin-left: auto;
  opacity: .2;
  text-decoration: underline;
  text-decoration-color: var(--color-black);
  text-decoration-skip-ink: none;
  text-decoration-thickness: 2px;
  text-underline-offset: -10px;

  .woocommerce-Price-currencySymbol,
  span.amount {
    color: var(--color-black);
    font-weight: var(--font-weight-semibold);
  }
}
```
